content:
  folders:
    - "docs"
    - "tests"
    - "notebooks"
    - "libs"
    - "classes"
    - "logs"
  files:
    - ".gitignore"
    - "README.md"
    - "requirements.txt"
    - "main.py"
    - "License"
    - "docs\\.gitkeep"
    - "tests\\.gitkeep"
    - "tests\\__init__.py"
    - "notebooks\\.gitkeep"
    - "notebooks\\__init__.py"
    - "libs\\.gitkeep"
    - "libs\\__init__.py"
    - "classes\\.gitkeep"
    - "classes\\__init__.py"
    - "logs\\.gitkeep"
    - "pytest.ini"
gitignore:
  - "*.pyc"
  - "__pycache__/"
  - ".pytest_cache/"
  - ".vscode/"
  - ".idea/"
  - "*.egg-info/"
  - "*.egg"
  - "*.dist"
  - "*.log"
  - "*.db"
  - "*.sqlite"
  - "*.bak"
  - "*.swp"
  - "*.swo"
  - "*.swm"
  - "*.swl"
  - "*.pyo"
  - "*.pyd"
  - ".venv/"
general:
  python_version: "3.8"
pytest:
  ini:
    - "webtest: mark a test as a webtest."
    - "slow: mark test as slow."
    - "prod: mark test as production."
    - "dev: mark test as development."
    - "project_only: mark test as a project test only.  This is designed for the developer and not the pipeline mandatory checks."
    - "gitpush: mark test as a git push mandatory test."
template:
    default: "cybereng\\v1"